### ISSUE TITLE
The same text displays differently in different browsers

### ISSUE THREAD

**Issue by alexandr-parkhomenko** [Versal/versal-gadget-api#73]
Please check this http://codepen.io/anon/pen/yyvNBx in Chrome and FireFox on Windows to see the issue.

**Comment by possibilities** [comment]
@merskin Alex has solved this in some gadget by using an open-sans package
on NPM... should we do that here or do you have other opinions? Thanks!

**Comment by possibilities** [comment]
oops tag failure ^^ /cc @mereskin

**Comment by mereskin** [comment]
Which package exactly?

**Comment by possibilities** [comment]
https://github.com/FontFaceKit/open-sans

**Comment by possibilities** [comment]
Really my point of tagging was you is for any advice how to solve the problem shown in the codepen. Some gadgets now fix it by using that package but obviously(?) we should fix it here.

**Comment by mereskin** [comment]
@alexandr-parkhomenko would you care to include screenshots from both Chrome and Firefox on windows so we can see it at a glance here?

@possibilities How exactly does this package solve the problem? What is the difference in linking to CDN vs local version of font?

**Comment by possibilities** [comment]
Also good questions for @alexandr-parkhomenko.

**Comment by alexandr-parkhomenko** [comment]
On my PC:
 
http://www.webpagescreenshot.info/img/54fecfb44c5ed4-70545080 - Google Chrome 40.0.2214.115 m
http://imagizer.imageshack.com/img661/7203/stRqaC.png - FireFox 35.01

I checked issue on other PCs with Windows 7 and didn't find this issue, so issue could be closed.

**Comment by possibilities** [comment]
Oh cool, it was a problem with your environment @alexandr-parkhomenko ?

**Comment by alexandr-parkhomenko** [comment]
Yes
